basePath: /api/v1/
definitions:
  controller.CommonResult:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  controller.Page:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  controller.ResultWithPage:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
      page:
        $ref: '#/definitions/controller.Page'
    type: object
  hostapi.HostInfo:
    properties:
      hostId:
        type: string
      hostIp:
        type: string
      hostName:
        type: string
    type: object
  instanceapi.InstanceInfo:
    properties:
      instanceId:
        type: string
      instanceName:
        type: string
      instanceStatus:
        type: integer
      instanceVersion:
        type: integer
    type: object
  userapi.UserIdentity:
    properties:
      userName:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: zhangpeijin@pingcap.com
    name: zhangpeijin
  description: TiCP UI API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: TiCP UI API
  version: "1.0"
paths:
  /host/query:
    post:
      consumes:
      - application/json
      description: 查询主机
      parameters:
      - description: 登录token
        in: header
        name: Token
        required: true
        type: string
      - description: 页码
        in: body
        name: page
        schema:
          type: integer
      - description: 每页数量
        in: body
        name: pageSize
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.ResultWithPage'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/hostapi.HostInfo'
                  type: array
              type: object
      summary: 查询主机接口
      tags:
      - resource
  /instance/create:
    post:
      consumes:
      - application/json
      description: 创建实例
      parameters:
      - description: 登录token
        in: header
        name: Token
        required: true
        type: string
      - description: 实例名
        in: body
        name: instanceName
        required: true
        schema:
          type: string
      - description: 实例版本
        in: body
        name: instanceVersion
        required: true
        schema:
          type: integer
      - description: 数据库密码
        in: body
        name: dbPassword
        required: true
        schema:
          type: string
      - description: PD数量
        in: body
        name: pdCount
        required: true
        schema:
          type: integer
      - description: TiDB数量
        in: body
        name: tiDBCount
        required: true
        schema:
          type: integer
      - description: TiKV数量
        in: body
        name: tiKVCount
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResult'
            - properties:
                data:
                  $ref: '#/definitions/instanceapi.InstanceInfo'
              type: object
      summary: 创建实例接口
      tags:
      - instance
  /instance/query:
    post:
      consumes:
      - application/json
      description: 查询实例
      parameters:
      - description: 登录token
        in: header
        name: Token
        required: true
        type: string
      - description: 页码
        in: body
        name: page
        schema:
          type: integer
      - description: 每页数量
        in: body
        name: pageSize
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.ResultWithPage'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/instanceapi.InstanceInfo'
                  type: array
              type: object
      summary: 查询实例接口
      tags:
      - instance
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 账户名
        in: body
        name: userName
        required: true
        schema:
          type: string
      - description: 账户密码
        in: body
        name: userPassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResult'
            - properties:
                data:
                  $ref: '#/definitions/userapi.UserIdentity'
              type: object
      summary: 登录接口
      tags:
      - platform
  /user/logout:
    post:
      consumes:
      - application/json
      description: 退出登录
      parameters:
      - description: 登录token
        in: header
        name: Token
        required: true
        type: string
      - description: 账户名
        in: body
        name: userName
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResult'
            - properties:
                data:
                  $ref: '#/definitions/userapi.UserIdentity'
              type: object
      summary: 退出登录
      tags:
      - platform
swagger: "2.0"
